### ISSUE TITLE
add test for alt = filename

### ISSUE THREAD

**Issue by muescha** [double-great/alt-text#62]
add test for:

alt text matches filename

```markdown
![myimage.png](./images/myimage.png)

![https://raw.githubusercontent.com/strapi/strapi-starter-gatsby-blog/master/medias/skip.png](https://raw.githubusercontent.com/strapi/strapi-starter-gatsby-blog/master/medias/skip.png "screen shot of sample cut and paste webhook url") 
```

**Comment by katydecorah** [comment]
Since this library only accepts the alt text value as input (not the file name) we have a rule that checks that the alt text doesn't end with an image file extension:

https://github.com/double-great/alt-text/blob/7676136283c9193965230d569e17ff883e388b42/clues.js#L124-L137

I'm going to close this issue, but please re-open if it doesn't help cover your use case.
